apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - ingress.yaml

commonLabels:
  app: ecommerce

images:
  - name: cart-service
    newTag: latest
  - name: order-service
    newTag: latest
  - name: inventory-service
    newTag: latest
  - name: notification-service
    newTag: latest
  - name: review-service
    newTag: latest
  - name: shipping-service
    newTag: latest